version: '3.8'

services:
  homepage-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: homepage-server
    restart: unless-stopped
    volumes:
      - homepage-data:/app/data
      - homepage-uploads:/app/static/uploads
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production

  homepage-admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: homepage-admin
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - API_HOST=homepage-server
      - API_PORT=4000
      - NODE_ENV=production
    depends_on:
      - homepage-server

volumes:
  homepage-data:
  homepage-uploads:
