name: Greetings

on:
  fork:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            感谢你提出第一个 Issue！我们会尽快查看并回复。
            在等待期间，请查阅 [文档](README.md) 和 [贡献指南](CONTRIBUTING.md)。
          pr-message: |
            感谢你提交第一个 Pull Request！你的贡献对我们意义重大。
            维护者会尽快进行代码审查。
